### ISSUE TITLE
Prepare database for upcoming features

### ISSUE THREAD

**Issue by oscarb** [oscarb/pinapple#27]
As a developer of the app, I want to add columns to the database in advance for upcoming features so that the risk of errors during upgrades is reduced.

This will also let users see when codes were added to Pinapple for codes added before the feature of presenting _date added_ to the user.

Columns that need to be added:
- [x] Archived? (see #4)
- [x] Category (see #8)
- [x] Manual sort order (see #9) 
- [x] Date added (see #22)
- [x] Pattern (see #26)

**Comment by oscarb** [comment]
Columns that need to be added:

- [ ] Archived? (see #4)
- [ ] Category (see #8)
- [ ] Manual sort order (see #9) 
- [ ] Date added (see #22)
- [ ] Pattern (see #26)

**Comment by oscarb** [comment]
Fixed in bb7cc5fbaf503a84ab1bacd915c316a7f676a5a1
